# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import file_sharing_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=file_sharing_app.models.group_file_name)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_sharing_app.Group')),
            ],
        ),
    ]
