# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing_app', '0002_groupfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupfile',
            old_name='name',
            new_name='title',
        ),
    ]
